Added tests for the Label Model and the Label Controller.
nofaralfasi/todo_list pull request #16
Opened 2022-05-12 15:34 UTC by nofaralfasi

Added some basics tests for the Label Model and the Label Controller.
Let me know if any other tests are needed and I will add them.

2022-05-13 10:50 UTC, stejskalleos requested changes
One small comment otherwise ready to merge

2022-05-13 10:50 UTC, stejskalleos commented on test/controllers/tasks_controller_test.rb
> +  # test 'should get index' do
Nit: If the are no other tests then we should remove the file

2022-05-13 10:50 UTC, stejskalleos commented on test/controllers/tasks_controller_test.rb
> +  # test 'should get index' do
Nit: If the are no other tests then we should remove the file

2022-05-15 07:26 UTC, Ron-Lavi approved these changes
Thanks @nofaralfasi ! LGTM 👍🏼

2022-05-15 07:27 UTC, merged